version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.1.0
jobs:
  unit-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet test -v n -l "console;verbosity=detailed"
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet build --version-suffix ${CIRCLE_BUILD_NUM} -c Release -o artifacts
  package:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: set
      - run:
          name: Build & Package
          command: |
            echo ${CIRCLE_TAG} | sed -E 's/v(.+)/\1/g'
            export VERSION=$(echo ${CIRCLE_TAG} | sed -E 's/v(.+)/\1/g')
            echo ${VERSION}
            dotnet publish -p:VersionPrefix=${VERSION} --version-suffix ${CIRCLE_BUILD_NUM} -c Release -o artifacts
            ls -lR artifacts
            mkdir tmp
            tar -czf tmp/CxAnalytix-${VERSION}-${CIRCLE_BUILD_NUM}.tar.gz -C artifacts/Release .
      - store_artifacts:
          path: tmp
workflows:
  version: 2
  ci:
    jobs:
      # Unit tests need to execute on .net core 3.1, commented until they do
      # - unit-test
      - build
          # requires:
          #   - unit-test
      - package:
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/



   

