version: 2.1
jobs:
  unit-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet test -v n -l "console;verbosity=detailed"
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run: dotnet build --version-suffix ${CIRCLE_BUILD_NUM} -c Release -o artifacts
  package:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    steps:
      - checkout
      - run:
          name: Build & Package
          command: |
            export VERSION=$(echo ${CIRCLE_TAG} | sed -E 's/v(.+)/\1/g')
            dotnet publish -p:VersionPrefix=${VERSION} --version-suffix ${CIRCLE_BUILD_NUM} -c Release -o artifacts
            mkdir tmp
            python .circleci/zip.py --output "tmp/CxAnalytix-${VERSION}-${CIRCLE_BUILD_NUM}.zip" --input artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - ./*

  publish-github-release:
      docker:
        - image: circleci/golang:1.9
      steps:
        - attach_workspace:
            at: tmp
        - run:
            name: "Publish Release on GitHub"
            command: |
              go get github.com/tcnksm/ghr
              ghr -t ${GITHUB_TOKEN} -u ${GITHUB_USER} -n ${CIRCLE_TAG} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} tmp/

workflows:
  version: 2
  ci:
    jobs:
      # Unit tests need to execute on .net core 3.1, commented until they do
      # - unit-test
      - build
          # requires:
          #   - unit-test
      - package:
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
      - publish-github-release:
          requires:
              - package



   

